In [2]:
import numpy as np
import scipy as sp

<h1>1.</h1>

$A = \begin{bmatrix}
0 & 2 \\
1 & 3 
\end{bmatrix}$

The first leading  element $a_{11} = 0$, which is zero, posing a problem for the standard LU decomposition without pivoting since the pivot element is zero.

However, we can still obtain the LU decomposition with row permutations (PLU decomposition), where $P$ is a permutation matrix.

1. Swap the rows of $A$ to have a non-zero pivot element:
$P = \begin{bmatrix}
0 & 1 \\
1 & 0 
\end{bmatrix},
\quad
PA = \begin{bmatrix}
1 & 3 \\
0 & 2 
\end{bmatrix}$

2. Perform the decomposition on $PA$ to obtain $L$ and $U$:
$L = \begin{bmatrix}
1 & 0 \\
0 & 1 
\end{bmatrix},
\quad
U = \begin{bmatrix}
1 & 3 \\
0 & 2 
\end{bmatrix}$

Since no further row operations are needed after the initial swap, the $L$ matrix remains the identity matrix, and the $U$ matrix is simply the $PA$ matrix.

Thus, the matrix $A$ can be decomposed into $LU$ with the help of a permutation matrix $P$.


In [3]:
A = np.array([[0,2],[1,3]])

P, L, U = sp.linalg.lu(A)

print(f"Permutation (P):\n{P}\n\nLower Triangular (L):\n{L}\n\nUpper Triangular (U):\n{U}")

Permutation (P):
[[0. 1.]
 [1. 0.]]

Lower Triangular (L):
[[1. 0.]
 [0. 1.]]

Upper Triangular (U):
[[1. 3.]
 [0. 2.]]


<h1>2.</h1>

$A = \begin{bmatrix}
10^{-22} & 2 \\
1 & 3 
\end{bmatrix}
=LU$

Firstly, we can proceed wit hGaussian elimination to for the upper triangular matrix $U$. The entry is $10^{-22}$, which is so small and we can treat it as zero in floating-point arithmetic.


Thus, through swapping rows and catch $10^{-22}$ as the multiplier which respond us ($R_2 - 10^{-22} \times R_1 \rightarrow R_2$):

$U = \begin{bmatrix}
1 & 3\\
10^{-22} - 1\times 10^{-22} & 2-3\times 10^{-22}
\end{bmatrix}$
$\approx
\begin{bmatrix}
1 & 3\\
0 & 2
\end{bmatrix}$ since $10^{-22}$ is negligible to be treated as 0.

The corresponding lower triangular matrix $L$, 
$L = \begin{bmatrix}
1 & 0\\
10^{-22} & 1
\end{bmatrix}$


In [4]:
#The LU Factorization
def myLU(A):
    n = A.shape[0] # get the dimension of the matrix A
    L = np.identity(n) # Build the identity part L
    U = A.astype(float) # start the U matrix as a copy of A, float type
    for j in range(0,n-1):
        for i in range(j+1,n):
            mult = U[i,j] / U[j,j]
            U[i, j+1:n] = U[i, j+1:n] - mult * U[j,j+1:n]
            L[i,j] = mult
            U[i,j] = 0 # Setting the lower part to zero
    return L,U

A = np.array([[1e-22, 2],[1,3]])
L, U = myLU(A)
print(f"Lower Triangular (L):\n{L}\n\nUpper Triangular (U):\n{U}")

Lower Triangular (L):
[[1.e+00 0.e+00]
 [1.e+22 1.e+00]]

Upper Triangular (U):
[[ 1.e-22  2.e+00]
 [ 0.e+00 -2.e+22]]


There exists a problem that the small leading entry dramatically affect the outcome:

$L = \begin{bmatrix}
1 & 0\\
10^{22} & 1
\end{bmatrix}
\quad
U = \begin{bmatrix}
10^{-22} & 2\\
0 & -2\times 10^{22}
\end{bmatrix}$

The influence of the small number $10^{-22}$ becomes extremely large and this results in a huge loss of numerical accuracy based on our $myLU()$ function.

Evidence is shown through the large positive number $10^{22}$ in $L$ and negative number $-2\times 10^{22}$ in $U$, where expresses the issue.

<h1>3.</h1>

The multiplication returns
$E_1 A = \begin{bmatrix}
4& -10&   2\\
1&  2&   3\\
2&   4&  2
\end{bmatrix}$

It seems reordering each row in matrix $A$ since the first 2 row of the identity matrix $E_1$ swaps, and this results in the same row operation in $A$. The first and second rows in $A$ swap with each other.

In [5]:
A = np.array([[1,2,3],
              [4,-10,2],
              [2,4,2]])

E1 = np.array([[0,1,0],
                [1,0,0],
                [0,0,1]])

E1A = np.dot(E1, A)
E1A

array([[  4, -10,   2],
       [  1,   2,   3],
       [  2,   4,   2]])

<h1>4.</h1>

When we are given a square matrix $A$, we can apply its identity matrix and then swap $i$-th and $j$-th rows which generates a square matrix $E_{ij}$ that, when applied to a matrix A, swaps rows i and j and leaves the other rows alone.

<h1>5.</h1>

Suppose a swap matrix $E_{ij}$ that exchanges its $i$-th and $j$-the row.</br>
Then, if we apply $E_{ij}$ to multiply itself, it will swap the rows back to its original positions. That's because we operates row swap twice, which resume their positions.</br>
As $E_{ij}$ is one identity matrix with $i$-th and $j$-th rows exchanged, this implies that $E_{ij} \cdot E_{ij} = I$, where $I$ represents identity matrix.</br>
This shows that the inverse of $E_{ij}$ is itself since $E_{ij}^{-1} \cdot E_{ij} = I$</br>
Thus, $E_{ij}^{-1} = E_{ij}$

<h1>6.</h1>

$$A = \begin{bmatrix}
1 & 2 & 4 \\
4 & -10 & 2 \\
2 & 4 & 2 
\end{bmatrix}$$

Try to get $U$:

Since 4 is the largest number in the first row, so swap the first and second rows, which gives:
$$E_1 = \begin{bmatrix}
0 & 1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1 \\
\end{bmatrix} \quad
E_1A = \begin{bmatrix}
4 & -10 & 2 \\
1 & 2 & 4 \\
2 & 4 & 2 
\end{bmatrix}$$


Then, eliminate the first entries in row 2 and row 3:
$$L_1 = \begin{bmatrix}
1 & 0 & 0 \\
-\frac{1}{4} & 1 & 0 \\
-\frac{1}{2} & 0 & 1 
\end{bmatrix} \quad
L_1E_1A = \begin{bmatrix}
4 & -10 & 2 \\
0 & \frac{9}{2} & \frac{5}{2} \\
0 & 9 & 1
\end{bmatrix}$$

Now, the number 9 in the third row, second column become the largest one, so swap row 3 and row 2, which gives:
$$E_2 = \begin{bmatrix}
1 & 0 &0\\
0 & 0 & 1\\
0 & 1 & 0
\end{bmatrix} \quad
E_2L_1E_1A = \begin{bmatrix}
4& -10 & 2\\
0 &  9 &  1\\
0  & \frac{9}{2} & \frac{5}{2} 
\end{bmatrix}$$

From this, we need to eliminate the second entry in the third row, which is $\frac{9}{2}$, which means that we can apply $L_2$:
$$L_2 = \begin{bmatrix}
1&   0& 0\\
0& 1&   0\\
0& -\frac{1}{2}& 1
\end{bmatrix} \quad
L_2E_2L_1E_1A = \begin{bmatrix}
4& -10 &2\\
0 & 9 &  1\\
0 & 0 & 2
\end{bmatrix}$$
which represents the upper triangular matrix 
$U = \begin{bmatrix}
4& -10 &2\\
0 & 9 &  1\\
0 & 0 & 2
\end{bmatrix}
= L_2E_2L_1E_1A$


In [6]:
A = np.array([[1,2,3],
              [4,-10,2],
              [2,4,2]])

# initialize E1 as an identity matrix
E1 = np.identity(3)

# Swap the first and second row for E1 to set the row__1's first entry matching the largest number of 4 in the first column
E1[[0,1]] = E1[[1,0]]

# apply E1 to A
E1A = np.dot(E1, A)
print(f'E1A:\n{E1A}')

# initialize L1 as an identity matrix
L1 = np.identity(3)

# eliminating the second and third rows' first entries
L1[1, 0] = -E1A[1, 0] / E1A[0, 0]
L1[2, 0] = -E1A[2, 0] / E1A[0, 0]
print(f'L1:\n{L1}')
L1E1A = L1@E1A
print(f'L1E1A:\n{L1E1A}')

# initialize E2 
E2 = np.identity(3)

# Swap the second and third rows
E2[[1,2]] = E2[[2,1]]

# apply  E2 to L1E1A
E2L1E1A = np.dot(E2, L1E1A)
print(f'E2L1E1A:\n{E2L1E1A}')

# initialize L2
L2 = np.identity(3)

# eliminating the second entry in the third row
L2[2, 1] = -E2L1E1A[2, 1] / E2L1E1A[1, 1]
print(f'L2:\n{L2}')
L2E2L1E1A = np.dot(L2, E2L1E1A)
print(f'L2E2L1E1A:\n{L2E2L1E1A}')

E1A:
[[  4. -10.   2.]
 [  1.   2.   3.]
 [  2.   4.   2.]]
L1:
[[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [-0.5   0.    1.  ]]
L1E1A:
[[  4.  -10.    2. ]
 [  0.    4.5   2.5]
 [  0.    9.    1. ]]
E2L1E1A:
[[  4.  -10.    2. ]
 [  0.    9.    1. ]
 [  0.    4.5   2.5]]
L2:
[[ 1.   0.   0. ]
 [ 0.   1.   0. ]
 [ 0.  -0.5  1. ]]
L2E2L1E1A:
[[  4. -10.   2.]
 [  0.   9.   1.]
 [  0.   0.   2.]]


<h1>7.</h1>

In [7]:
# From the previous matrices in Problem 6.
P = np.dot(E2, E1)
print(f'P:\n{P}')

L = E2 @ E1 @ np.linalg.inv(E1) @ np.linalg.inv(L1) @ np.linalg.inv(E2) @ np.linalg.inv(L2)
print(f"L:\n{L}")

# Check if PA = LU
U = L2E2L1E1A
PA = np.dot(P, A)
LU = np.dot(L, U)
print(f'If PA = LU:\n{PA == LU}')
print(f"\nBy testing the previous example, PA = LU, which giving:\nPA =\n{PA} \nLU =\n{LU}")

P:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L:
[[1.   0.   0.  ]
 [0.5  1.   0.  ]
 [0.25 0.5  1.  ]]
If PA = LU:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

By testing the previous example, PA = LU, which giving:
PA =
[[  4. -10.   2.]
 [  2.   4.   2.]
 [  1.   2.   3.]] 
LU =
[[  4. -10.   2.]
 [  2.   4.   2.]
 [  1.   2.   3.]]


<h1>8.</h1>

In [8]:
import numpy as np

def myPLU(A):
    # number of rows in the matrix A, which is also the size of the square matrices L, U, and P
    n = A.shape[0]

    # Initialize the lower triangular matrix L as an identity matrix of size n
    L = np.identity(n)

    # Initialize the upper triangular matrix U as a copy of A
    U = np.copy(A)

    # Initialize the permutation matrix P as an identity matrix of size n
    P = np.identity(n)

    # Loop over each column of the matrix A for the PLU decomposition
    for j in range(0, n-1):
        # Find the index of the pivot row by locating the maximum absolute value in the current column j below or at row j
        pivot_row = np.argmax(np.abs(U[j:, j])) + j

        # Swap the current row j with the pivot row in matrix U for partial pivoting
        U[[j, pivot_row]] = U[[pivot_row, j]]

        # Perform row swap in matrix P to record the permutation
        P[[j, pivot_row]] = P[[pivot_row, j]]

        # Update the lower triangular matrix L with the multipliers used in the elimination steps
        for k in range(0, j):
            L[[j, pivot_row], k] = L[[pivot_row, j], k]

        # Loop over the rows below the pivot row to eliminate the current column entries
        for i in range(j+1, n):
            # Calculate the multiplier to be used to eliminate the entry in column j of row i
            mult = U[i, j] / U[j, j]

            # Subtract the appropriate multiple of the pivot row from the current row to make the current column entry 0
            U[i, j+1:n] = U[i, j+1:n] - mult * U[j, j+1:n]

            # Store the multiplier in the lower triangular matrix L
            L[i, j] = mult

            # Ensure that the current lower parts are 0
            U[i, j] = 0

    # Return the permutation matrix P, the lower triangular matrix L, and the upper triangular matrix U
    return P, L, U

<h1>9.</h1>

In [9]:
# Test for myPLU() function
A = np.array([[1,2,3],
              [4,-10,2],
              [2,4,2]])

P, L, U = myPLU(A)

P, L, U, L@U
# seems not returning the correct LU decomposition, but the right P.
# Maybe the new pivot is not at the same previous position since the row operation?

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[1.        , 0.        , 0.        ],
        [0.5       , 1.        , 0.        ],
        [0.25      , 0.44444444, 1.        ]]),
 array([[  4, -10,   2],
        [  0,   9,   1],
        [  0,   0,   1]]),
 array([[  4.        , -10.        ,   2.        ],
        [  2.        ,   4.        ,   2.        ],
        [  1.        ,   1.5       ,   1.94444444]]))

# Revised myPLU() function:

In [10]:
def PLU(A): # A is a square matrix
    A = A.astype(float)
    n = A.shape[0]
    L = np.identity(n)
    U = A.copy()
    P = np.identity(n)
    
    for j in range(n):
        pivot_row = np.argmax(np.abs(U[j:, j]))+j
        
        # if the pivot row is not the current row
        if j != pivot_row:
            U[[j, pivot_row], :] = U[[pivot_row, j], :]
            P[[j, pivot_row],:] = P[[pivot_row, j],:]
            L[[j,pivot_row], :j] = L[[pivot_row, j], :j]
            
        for i in range(j+1, n):
            L[i,j] = U[i,j]/U[j,j]
            U[i, j:] = U[i, j:] - L[i, j] * U[j, j:]
            U[i,j] = 0
            
    return P, L, U

# Test for PLU() function
A = np.array([[1,2,3],
              [4,-10,2],
              [2,4,2]])

P, L, U = PLU(A)

P, L, U, L@U


(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[1.  , 0.  , 0.  ],
        [0.5 , 1.  , 0.  ],
        [0.25, 0.5 , 1.  ]]),
 array([[  4., -10.,   2.],
        [  0.,   9.,   1.],
        [  0.,   0.,   2.]]),
 array([[  4., -10.,   2.],
        [  2.,   4.,   2.],
        [  1.,   2.,   3.]]))

# Using PLU Decomposition to solve the system $Ax = b$

In [11]:
def PLUsolve(A, b):
    A = A.astype(float)
    
    def PLU(A): # A is a square matrix
        A = A.astype(float)
        n = A.shape[0]
        L = np.identity(n)
        U = A.copy()
        P = np.identity(n)
    
        for j in range(n):
            pivot_row = np.argmax(np.abs(U[j:, j]))+j
        
            # if the pivot row is not the current row
            if j != pivot_row:
                U[[j, pivot_row], :] = U[[pivot_row, j], :]
                P[[j, pivot_row],:] = P[[pivot_row, j],:]
                L[[j,pivot_row], :j] = L[[pivot_row, j], :j]
            
            for i in range(j+1, n):
                L[i,j] = U[i,j]/U[j,j]
                U[i, j:] = U[i, j:] - L[i, j] * U[j, j:]
                U[i,j] = 0
            
        return P, L, U

    def forward_substitution(L, Pb):
        n = Pb.size
        # solve Ly = Pb for y
        y = np.zeros((n,1))
        for i in range(n):
            y[i] = Pb[i] 
            for j in range(i): # now adjust y 
                y[i] = y[i] - L[i,j] * y[j] 
        return y

    def backward_substitution(U, y):
        n = y.size
        # solve Ux= y for x
        x = np.zeros((n,1))
        for i in reversed(range(n)):
            x[i] = y[i]/U[i, i]
        
            for j in range(i+1, n):
                x[i] = x[i] - U[i, j]*x[j]/U[i,i]
        return x

    # Perform PLU decomposition
    P, L, U = PLU(A)
    
    # Find Pb vector
    Pb = np.dot(P, b)

    # Solve for y using forward substitution
    y = forward_substitution(L, Pb)

    # Solve for x using back substitution
    x = backward_substitution(U, y)

    return x


# Test the PLUsolve function with random numbers
m = 3
A = np.random.rand(m, m)
b = np.random.rand(m, 1)
sol = PLUsolve(A, b)
print(f"A:\n{A}\nb:\n{b}\nx:\n{sol}")

# Check if Ax = b, consider machine precision
print(f"\nDifference between Ax and b:\n{np.abs(A@sol - b)}")

A:
[[0.81039844 0.95991032 0.91963345]
 [0.28315136 0.21557508 0.71825896]
 [0.25321033 0.81781116 0.47913528]]
b:
[[0.15318002]
 [0.4677943 ]
 [0.26293233]]
x:
[[-1.03484589]
 [ 0.0258815 ]
 [ 1.0514772 ]]

Difference between Ax and b:
[[1.38777878e-16]
 [1.11022302e-16]
 [0.00000000e+00]]


In [12]:
A = np.array([[1,2,3],
              [4,-10,2],
              [2,4,2]])

P, L, U = sp.linalg.lu(A)
P, L, U, L@U

(array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[1.  , 0.  , 0.  ],
        [0.5 , 1.  , 0.  ],
        [0.25, 0.5 , 1.  ]]),
 array([[  4., -10.,   2.],
        [  0.,   9.,   1.],
        [  0.,   0.,   2.]]),
 array([[  4., -10.,   2.],
        [  2.,   4.,   2.],
        [  1.,   2.,   3.]]))